Dev polina
alexandermorozzov/transport_frames pull request #23
Opened 2024-07-03 14:09 UTC by blackcoster

2024-07-05 10:06 UTC, GeorgeKontsevik requested changes

2024-07-05 10:06 UTC, GeorgeKontsevik commented on transport_frames/src/metrics/indicators.py
> +    for service in ['railway_stops', 'fuel', 'ports', 'local_aero', 'international_aero','water_objects','oopt']:
тут чот много оверлэев не? мб можно это как-то иначе это сделать один раз? И потом мб посчитать кто из них к какому сервису относится? как идея

2024-07-05 10:06 UTC, GeorgeKontsevik commented on transport_frames/src/metrics/indicators.py
> +    filtered_regions_terr = regions_gdf[regions_gdf.intersects(neud.unary_union)]
мб через Pool (в мультипроцессинг или как-то еще) можно операции разнести по разным потокам? Хз как это правильно делается

2024-07-05 10:06 UTC, GeorgeKontsevik commented on transport_frames/src/metrics/indicators.py
> +    G = assign_services_names_to_nodes({'nearest_region_centers':filtered_region_centers},momepy.nx_to_gdf(G)[0],G)
момепу ту гдф третий раз повторяется -- это вроде дорогая операция, кажется ее можно вообще отсюда вынести?

2024-07-05 10:06 UTC, GeorgeKontsevik commented on transport_frames/src/metrics/indicators.py
> +    merged['to_settlement_center'],merged['to_region_center'] = dijkstra_nearest_centers(G)
это вроде тоже отсюда выносится?

2024-07-05 10:06 UTC, GeorgeKontsevik commented on transport_frames/src/metrics/indicators.py
> +    merged.drop(columns=['geometry','x','y'],inplace=True)
мб раньше дропнуть лишние столбцы?

2024-07-05 10:06 UTC, GeorgeKontsevik commented on transport_frames/src/metrics/indicators.py
> +    merged.replace(['inf'], None, inplace=True)
мб раньше это как-то обработать?

2024-07-05 10:17 UTC, blackcoster commented on transport_frames/src/metrics/indicators.py
> +    if territory:
да, это внутри функции вызывается там все норм, будет ток тру или фолс

2024-07-05 10:27 UTC, blackcoster commented on transport_frames/src/metrics/indicators.py
> +        max_distance=120000,
а, это я тестила, надо обратно вернуть
расстояние на котором ищем ноды для проецирования

2024-07-05 10:28 UTC, blackcoster commented on transport_frames/src/metrics/indicators.py
> +def indicator_territory(G,neud,local_crs,regions_gdf,points,region_centers,services):
yes, переименую

2024-07-05 10:29 UTC, blackcoster commented on transport_frames/src/metrics/indicators.py
> +    n,e = momepy.nx_to_gdf(G)
да вообще нет, тут вся функция вообще за 7 сек отрабатывает

2024-07-05 12:27 UTC, blackcoster commented on transport_frames/src/metrics/indicators.py
> +    merged['to_settlement_center'],merged['to_region_center'] = dijkstra_nearest_centers(G)
не, тут nearest centers выбираются ближайшие к поданной территории на основе разметки нод

2024-07-12 12:42 UTC, GeorgeKontsevik approved these changes

2024-07-12 13:38 UTC, merged